[16.0][MIG] crm_claim_corrective: Migration to 16.0
avanzosc/crm-addons pull request #129
Opened 2023-12-27 09:05 UTC by unaiberis

2024-03-01 12:36 UTC, anajuaristi approved these changes

2024-03-01 12:36 UTC, anajuaristi commented
It works but needs several usability improvement. By the moment LGTM 👍 
@oihane

2024-03-01 12:48 UTC, oihane requested changes
Hay cambios no relacionados con el modulo que se pretende añadir, eliminar dichos cambios

2024-03-27 12:00 UTC, anajuaristi approved these changes

2024-04-12 08:38 UTC, anajuaristi approved these changes

2024-04-12 09:24 UTC, merged