[16.0][MIG] crm_claim_related: Migration to 16.0
avanzosc/crm-addons pull request #132
Opened 2023-12-28 10:18 UTC by unaiberis

2024-03-01 12:11 UTC, anajuaristi approved these changes

2024-03-01 12:12 UTC, anajuaristi commented
Functionally tested LGFM 👍 
@oihane please test technically and merge

2024-03-01 12:48 UTC, oihane requested changes
Hay cambios no relacionados con el modulo que se pretende añadir, eliminar dichos cambios

2024-04-12 09:41 UTC, anajuaristi approved these changes

2024-04-12 09:43 UTC, anajuaristi commented
@oihane unblock please

2024-04-12 09:48 UTC, merged