[ADD] crm_extended_address && website_crm_extended_address
avanzosc/crm-addons pull request #40
Opened 2020-04-15 11:31 UTC by adrianrevilla009

2020-04-15 13:08 UTC, oihane requested changes
Revisa los errores en https://travis-ci.com/github/avanzosc/crm-addons/jobs/319577271

En los XML estas usando tabuladores en vez de espacios

2020-04-15 13:08 UTC, oihane commented on website_crm_extended_address/controllers/__init__.py
> +# -*- coding: utf-8 -*-
Estas usando python3 esta línea sobra

2020-04-15 13:08 UTC, oihane commented on website_crm_extended_address/controllers/website_contact.py
> +        return http.request.render('website.contactus', values)
¿Para que haces esto?

2020-04-15 13:08 UTC, oihane commented on website_crm_extended_address/controllers/website_contact.py
> +
Demasiadas líneas en blanco

2020-04-15 13:09 UTC, oihane commented on crm_extended_address/models/crm_lead.py
> +    sending_street = fields.Char(string='Sending street', readonly=False)
El nombre del campo debe ser shipping_***

2020-04-22 13:23 UTC, oihane commented
Para modificar y extender el modulo website_crm puedes mirar este modulo: https://github.com/avanzosc/custom-addons/tree/8.0/rockbotic_website_crm en el puedes ver como funciona el añadir nuevos campos en el lead y como tratarlos en el website de contacto.
Yo creo que ni el javascript ni el css son necesarios. dado que solo es añadir nuevos campos y que estos se recojan en la iniciativa. Veras que en el modulo que te paso no se hacen cambios ni en css ni en js.

2020-07-02 13:13 UTC, Daniel-CA commented
Adrian puedes arreglar los errores de Flake8?

2020-07-03 07:02 UTC, adrianrevilla009 commented
Si, voy a borrar este pull y voy a subir de uno en uno los módulos.

2020-07-03 07:02 UTC, closed without merging