[ADD] crm_phonecall_inbound: New object phonecall inbound.
avanzosc/crm-addons pull request #60
Opened 2021-06-03 14:02 UTC by Berezi

2021-06-03 14:07 UTC, Berezi commented
@anajuaristi @oihane @alfredoavanzosc @Daniel-CA review please.

2021-06-03 14:36 UTC, alfredoavanzosc commented on crm_phonecall_inbound/models/crm_phonecall_inbound.py
> +            ("open", "Confirmed"),
Los literales los debes de meter entre _(), para que se puedan traducir, es decir _("Confirmed")

2021-06-03 14:36 UTC, alfredoavanzosc commented on crm_phonecall_inbound/models/crm_phonecall_inbound.py
> +        selection=[("0", "Low"), ("1", "Normal"), ("2", "High")],
Aqui tambien _()

2021-06-03 17:49 UTC, anajuaristi requested changes

2021-06-03 17:49 UTC, anajuaristi commented on crm_phonecall_inbound/models/crm_phonecall_inbound.py
> +            ("open", "Confirmed"),
Pero no hay que hacer ningún objeto nuevo!!!
NO SE qué se está liando aquí pero no se ha leido el texto de mi claim.
Por favor, es CRITICO que se lean las especificaciones.
Pone... crear un NUEVO MENU con unas ciertas condiciones. Una vista FORM y unos datos por defecto. No tiene ningún sentido tener 2 objetos phonecall, ni que éste sea un módulo nuevo.
Este PR no vale.

2021-06-15 16:05 UTC, oihane requested changes, later dismissed
Hay que revisar los avisos y errores que da travis, no dejar que el PR esté rojo para siempre.
```
crm_phonecall_inbound/models/crm_phonecall.py:27:80: E501 line too long (85 > 79 characters)
crm_phonecall_inbound/models/crm_phonecall.py:29:80: E501 line too long (81 > 79 characters)
crm_phonecall_inbound/models/crm_phonecall.py:66:56: W291 trailing whitespace
```

2021-06-15 16:05 UTC, oihane commented on crm_phonecall_inbound/views/crm_phonecall_views.xml
> +</odoo>
falta salto de linea

2021-06-16 07:15 UTC, Berezi commented on crm_phonecall_inbound/views/crm_phonecall_views.xml
> +</odoo>
Este PR se subió para que Ana le enseñara lo que habíamos hecho a Asterix. Pero todavía habrá cambios. Es por eso que no está corregido.

2021-06-29 10:24 UTC, Berezi commented
@anajuaristi @Daniel-CA @oihane @alfredoavanzosc review please.

2021-07-07 13:54 UTC, Berezi commented
@anajuaristi @oihane @alfredoavanzosc @Daniel-CA review please.

2021-09-01 08:19 UTC, oihane commented on crm_phonecall_inbound/wizards/crm_phonecall_transfer.py
> +        string='Commercial partner', comodel_name='res.users')
si el comodel es res.user, no puede llamarse el campo partner_id... el commercial_partner_id es la entidad comercial del partner, que suele ser el "padre" de un contacto o si mismo si es una compañia.

2021-09-20 09:04 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-09-20 09:25 UTC, anajuaristi commented on crm_phonecall_inbound/__manifest__.py
> +        "hr_recruitment"
Dependentzi hau zergaitik?

2021-09-20 09:25 UTC, anajuaristi commented on crm_phonecall_inbound/models/crm_phonecall.py
> +    phonecall_ids = fields.One2many(
phonecall_ids ezin du izen, ze badirudi bere buruarekin dagoela linkatuta
Izatekotan phonecall_time_ids

2021-09-20 09:25 UTC, anajuaristi commented on crm_phonecall_inbound/models/crm_phonecall.py
> +    commercial_partner_id = fields.Many2one(
Commercial partner id, izengoa related al partner que ya tiene phonecall. 
Ez da kanpo suelto bat. Horrela, inkonsistentziak sortu daitekezke

2021-09-20 09:25 UTC, anajuaristi commented on crm_phonecall_inbound/models/crm_phonecall.py
> +                self.commercial_partner_id = self.partner_id.parent_id.id
Related bada, hau ez da beharrezkoa

2021-09-20 09:25 UTC, anajuaristi commented on crm_phonecall_inbound/models/crm_phonecall.py
> +        vals = {'name': self.name,
Hau beste modulo baten izan beharko luke eta hemen jartzen badezu, CRMkin dependentzia beharko luke. 
crm_phonecall_lead edo horrelakoren bat izan beharko luke.

2021-09-20 09:25 UTC, anajuaristi commented on crm_phonecall_inbound/models/crm_phonecall_time.py
> +    team_id = fields.Many2one(string='Sales team', comodel_name='crm.team')
team_id default jarri daiteke el self.env.user.team_id

2021-09-20 09:25 UTC, anajuaristi commented on crm_phonecall_inbound/wizards/crm_phonecall_transfer.py
> +    team_id = fields.Many2one(string='Sales team', comodel_name='crm.team')
Berdin, defektuz, team_id izangoa user_id-ren ekipoa

2021-09-21 10:41 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-11-05 12:51 UTC, anajuaristi approved these changes

2021-11-05 12:53 UTC, Daniel-CA approved these changes

2021-11-05 12:53 UTC, merged