[ADD] crm_phonecall_claim: Many to many from phone call inbounds to c…
avanzosc/crm-addons pull request #61
Opened 2021-06-03 14:06 UTC by Berezi

…laims.

2021-06-03 14:07 UTC, Berezi commented
@oihane @alfredoavanzosc @anajuaristi @Daniel-CA review please.

2021-06-03 14:20 UTC, oihane commented
No pasará travis hasta fusionar #60

2021-06-16 09:47 UTC, oihane requested changes, later dismissed
Si has eliminado el objeto crm.phonecall.inbound todo este modulo está mal.

2021-06-29 12:04 UTC, Berezi commented
@oihane @anajuaristi @Daniel-CA @alfredoavanzosc review please.

2021-06-30 15:20 UTC, oihane commented
Ni estás realizando test (cosa que se ejecuta y ya) ni estás probando manualmente el modulo, porque este modulo **VA A FALLAR**, ya que con los cambios hechos a `crm_phonecall_inbound` el objeto `crm.phonecall.inboud` **YA NO EXISTE**

Además este modulo debería de ser un enlace entre `crm_phonecall` y `crm_claim`

2021-07-01 08:20 UTC, Berezi commented
Bai barkau. Aldaketai gabe igo nun.

2021-09-20 09:24 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-09-20 11:43 UTC, Daniel-CA approved these changes

2021-09-20 11:53 UTC, anajuaristi commented on crm_phonecall_claim/__manifest__.py
> +        "crm_phonecall_inbound",
Dependas crm_phonecall

2021-09-20 11:53 UTC, anajuaristi commented on crm_phonecall_claim/__manifest__.py
> +        "crm_phonecall_inbound",
Depends crm_phonecall
zuk eindako moduluarekin ez dauka inongo dependentzirik

2021-09-20 11:53 UTC, anajuaristi commented on crm_phonecall_claim/models/crm_claim.py
> +        string="Phone call inbound",
Phone call, ez da inbound. Izan daitezke inbound eta outbound (entrantes y salientes) 
Claim bat dago lotuta dei batekin. Ez dio axola entrante o saliente den

2021-09-20 11:53 UTC, anajuaristi commented on crm_phonecall_claim/models/crm_claim.py
> +        string='Phone call inbound', comodel_name='crm.phonecall')
Phone call

2021-09-20 11:53 UTC, anajuaristi commented on crm_phonecall_claim/views/crm_claim_views.xml
> +                        <field string="Inbound phone calls" name="count_phonecall" widget="statinfo"/>
Phone call

2021-09-21 10:40 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-09-21 16:52 UTC, anajuaristi approved these changes

2021-09-21 16:52 UTC, merged